[FIX]: CUDA threads for Eddy
PennLINC/qsiprep pull request #788
Opened 2024-07-19 22:00 UTC by araikes

Eddy is currently getting threads from `omp_nthreads`. However, eddy_cuda only works if `--nthr=1`. This will set the threads for eddy depending on the `use_cuda` key in eddy_config. Fixes #747.

Tested locally and it works. Will not catch the cases where `use_cuda` is True but no GPU is passed to container and then reverts to `eddy_cpu`

2024-07-22 23:40 UTC, araikes commented
@mattcieslak,

So, I added this right before you released `v0.22.0`. I assume it will still work, given the minimal change to the workflow.

2024-07-24 16:42 UTC, mattcieslak requested changes
One tiny change and this is perfect. Thanks @araikes!

2024-07-24 16:42 UTC, mattcieslak commented on qsiprep/workflows/dwi/fsl.py
> +    if eddy_args["use_cuda"] is True:
```suggestion
    if eddy_args["use_cuda"]:
```

2024-07-24 19:42 UTC, mattcieslak approved these changes

2024-07-24 19:42 UTC, merged